/* changelog.js — v1.38.0
 * Statisch generierte Versions-Historie fuer den vertikalen Zeitstrahl,
 * der beim Klick auf .version-tag angezeigt wird.
 * Neue Releases OBEN einfuegen.
 */
window.VEXBOB_CHANGELOG = [
    { v: 'v1.40.0', date: '2026-09-02', title: 'Gesundheit: Import-Protokoll mit Payload-Download', notes: [
        'Jeder automatische Sync der Auto-Health-Export-App wird jetzt mit seinem Roh-Payload gespeichert (neue Tabelle health_import_log, Migration 025).',
        'Neue Karte "Import-Protokoll" in den Gesundheits-Einstellungen: Zeitpunkt, Format, Dateiname, Größe, Ingest-Ergebnis und Vorschau je Aufruf — plus Download der Originaldatei zum Abgleich mit den importierten Werten.',
        'Einzelne Einträge löschbar, Protokoll komplett leerbar. Aufbewahrt werden die letzten 200 Aufrufe je Nutzer, Payloads über 5 MB werden gekürzt (ENV HEALTH_IMPORT_LOG_KEEP / HEALTH_IMPORT_LOG_MAX_BYTES).',
    ]},
    { v: 'v1.39.2', date: '2026-09-01', title: 'Vitalwerte: Ø-Linie als gleitender Trend', notes: [
        'Die Ø-Linie ist keine Waagrechte mehr, sondern ein zentriert gleitender Durchschnitt, der dem Verlauf folgt.',
        'Fensterbreite passt sich dem Zeitraum an (3 / 7 / 14 / 30 Werte), Messlücken bleiben weiterhin aussen vor.',
    ]},
    { v: 'v1.39.1', date: '2026-09-01', title: 'Gesundheit: Schlaf-Dopplung weg, Ø-Linie bei Vitalwerten', notes: [
        'Der kleine Schlaf-Insight auf der Übersicht ist entfallen — er rechnete mit den rohen asleep_minutes und zeigte daher weniger an als die Karte "Letzte Nacht" direkt daneben.',
        'Vitalwerte-Verlauf hat jetzt eine gestrichelte Ø-Linie.',
        'Ø, Min und Max ignorieren Messlücken: Werte unter 20 % des Medians (angebrochener heutiger Tag, Uhr nicht getragen, abgebrochener Sync) zählen nicht als Messwert. Die Anzahl ausgenommener Tage steht in der Statistikzeile.',
    ]},
    { v: 'v1.39.0', date: '2026-09-01', title: 'Duplikate: eigener Tab + ausblendbare Vorschläge', notes: [
        'Neue Seite "♻️ Duplikate" im Ausgaben-Subnav statt Karte auf dem Dashboard.',
        'Jeder Vorschlag hat jetzt ein "✕" zum dauerhaften Ausblenden, ohne die Bons zu löschen oder zusammenzuführen (neue Tabelle dismissed_expense_duplicates, Migration 024).',
    ]},
    { v: 'v1.38.7', date: '2026-09-01', title: 'Ausgaben-Übersicht: nur letzte 14 Tage + Aufklappen', notes: [
        'Dashboard-Liste zeigt standardmäßig nur Bons der letzten 14 Tage, darunter Button "Alle anzeigen" für ältere Einträge.',
        'Gilt nur ohne aktive Filter — sobald Zeitraum/Laden/Kategorie/Suche gesetzt ist, werden wie bisher alle Treffer direkt angezeigt.',
    ]},
    { v: 'v1.38.6', date: '2026-09-01', title: 'README komplett überarbeitet', notes: [
        'Von Changelog-artiger Feature-Liste (Versionsnummern in jedem Bullet) auf prägnante Beschreibung des aktuellen Stands umgestellt.',
        'Fehler behoben: Quickstart nannte JWT_SECRET statt korrektem ENV-Namen SECRET_KEY, Pfade zeigten auf nicht mehr existierendes Website/-Verzeichnis.',
        'Projekt-Struktur, Routers-Liste und Modul-Übersicht an tatsächlichen Code-Stand angeglichen (Blog ergänzt, veraltete Verweise entfernt).',
    ]},
    { v: 'v1.38.5', date: '2026-09-01', title: 'README aufgeräumt (Rezeptbuch/Fotos entfernt)', notes: [
        'Nie umgesetzte Platzhalter-Module Rezeptbuch und Fotos aus README (Subtitel, Feature-Liste, Projekt-Struktur) entfernt — beide waren nur "Coming soon"-Seiten ohne Backend oder Navigation.',
    ]},
    { v: 'v1.38.4', date: '2026-09-01', title: 'Sichtbare File-Inputs und Subnav-Rest weg', notes: [
        'Versteckte <input type=file>-Felder wurden von der globalen Form-Base ungewollt sichtbar gemacht — [hidden] jetzt mit !important abgesichert.',
        '"+ Neuer Bon"-Eintrag aus der Ausgaben-Subnav entfernt (jetzt nur noch ueber die Dashboard-Tiles).',
    ]},
    { v: 'v1.38.3', date: '2026-09-01', title: 'Neuer-Bon-Tiles im Homepage-Design', notes: [
        '4 Tiles im gleichen Look wie das Homepage-Dashboard: farbiges Icon-Badge + Titel + Kurztext.',
        'Kaste "Datei durchsuchen / hierher ziehen" entfernt.',
        'Drag & Drop laeuft jetzt unsichtbar auf der ganzen Seite mit temporaerem Overlay, das nur beim Draggen erscheint.',
    ]},
    { v: 'v1.38.2', date: '2026-09-01', title: 'Ausgaben-Dashboard: Neuer Bon direkt integriert', notes: [
        'Popup/Modal + FAB fuer "Neuer Bon" entfernt.',
        'Stattdessen Quick-Action-Karte oben im Dashboard: Kamera, Galerie, Einfuegen, Manuell.',
        'Drag & Drop-Zone und globaler Strg+V-Handler auf dem Dashboard.',
        'Bilder werden per sessionStorage an neu.html?src=dash uebergeben und starten dort automatisch den OCR-Flow.',
    ]},
    { v: 'v1.38.1', date: '2026-09-01', title: 'Hotfix: Ausgaben-Dashboard lud nicht', notes: [
        'Syntax-Fehler in dashboard.js (fehlende schliessende Klammer in renderActiveFilterChips) behoben — Seite blieb dadurch unsichtbar (body.visibility:hidden).',
    ]},
    { v: 'v1.38.0', date: '2026-09-01', title: 'Ausgaben-UX + Versions-Zeitstrahl', notes: [
        'Filter im Ausgaben-Dashboard hinter einem Popover versteckt (Suche + Presets bleiben sichtbar).',
        'Aktive Filter erscheinen als Zahl-Badge am Filter-Button.',
        '"+ Neuer Bon" oeffnet ein Modal direkt im Dashboard statt einer eigenen Seite.',
        'Klick auf die Versionszahl unten rechts oeffnet einen vertikalen Zeitstrahl mit allen Releases.',
    ]},
    { v: 'v1.37.2', date: '2026-08-31', title: 'Export-Aggregation korrekt', notes: [
        'Fix: bei aggregate=week|month wurden nicht alle Bereiche zusammengefasst.',
    ]},
    { v: 'v1.37.1', date: '2026-08-31', title: 'Zeitraum + Aggregation im Gesamt-Export', notes: [] },
    { v: 'v1.37.0', date: '2026-08-31', title: 'Toast/Confirm, Mobile Tab-Bar, SVG-Theme-Icon', notes: [
        'Modul-uebergreifender Toast/Confirm-Layer, Bottom-Tab-Bar auf Mobile.',
    ]},
    { v: 'v1.36.1', date: '2026-08-29', title: 'Schlaf-Fix + Icon-only Modul-Switcher', notes: [] },
    { v: 'v1.36.0', date: '2026-08-29', title: 'Design-Refresh (Glass Navbar, Hero, iOS-Tabs)', notes: [] },
    { v: 'v1.35.0', date: '2026-08-29', title: 'Migration-Checksums, Dry-Run, Sentry-Hook', notes: [] },
    { v: 'v1.34.0', date: '2026-08-29', title: 'Observability + Readiness-Probe', notes: [] },
    { v: 'v1.33.0', date: '2026-08-29', title: 'Backend-Haertung (Pool-Race, Timing-Attack, JSON)', notes: [] },
    { v: 'v1.32.0', date: '2026-08-29', title: ':where()-Form-Base, .btn-Utility, weg mit !important', notes: [] },
    { v: 'v1.31.0', date: '2026-08-29', title: 'CSS-Auslagerung, Print/Touch/SEO', notes: [] },
    { v: 'v1.30.0', date: '2026-08-29', title: 'P0/P1 CSS-Fixes (A11y, FOUC, Design-Tokens)', notes: [] },
    { v: 'v1.29.2', date: '2026-08-28', title: 'CSV-Exports mit UTF-8-BOM', notes: [] },
    { v: 'v1.29.1', date: '2026-08-28', title: 'Fix Schlaf-KPIs bei fehlenden Werten', notes: [] },
    { v: 'v1.29.0', date: '2026-08-28', title: 'CSV-Import 1:1, Rescale entfernt', notes: [] },
    { v: 'v1.28.1', date: '2026-08-28', title: 'Fix Startup-Crash (slowapi)', notes: [] },
    { v: 'v1.28.0', date: '2026-08-28', title: 'Health-Datensaetze loeschen', notes: [] },
    { v: 'v1.27.0', date: '2026-08-28', title: 'Health-CSV im Gesamt-Export', notes: [] },
    { v: 'v1.26.0', date: '2026-08-28', title: 'Uebertrag vom Puffer aufs Sparziel', notes: [] },
    { v: 'v1.25.1', date: '2026-08-28', title: 'Workouts inline + Schlaf-Empty-State', notes: [] },
    { v: 'v1.25.0', date: '2026-08-28', title: 'Health-Seite modernisiert', notes: [] },
    { v: 'v1.24.0', date: '2026-08-28', title: 'CSV-basierter Health-Import', notes: [] },
    { v: 'v1.23.2', date: '2026-08-28', title: 'Hotfix Crash-Loop (health_router)', notes: [] },
    { v: 'v1.23.1', date: '2026-08-28', title: 'Manueller JSON-Import (Health)', notes: [] },
    { v: 'v1.23.0', date: '2026-08-28', title: 'Gesamt-Export (Sparziel+Ausgaben+Health)', notes: [] },
    { v: 'v1.22.1', date: '2026-08-28', title: 'Fix: hKeyModal blockierte Klicks', notes: [] },
    { v: 'v1.22.0', date: '2026-08-28', title: 'Health-Modul (Auto Health Export Sync)', notes: [] },
    { v: 'v1.21.3', date: '2026-08-26', title: 'Fix Produkte-Seite unsichtbar', notes: [] },
    { v: 'v1.21.2', date: '2026-08-26', title: 'Fix HTTP 500 auf Produkt-Seite', notes: [] },
    { v: 'v1.21.1', date: '2026-08-26', title: 'SW Auto-Update, Blog-Menue, GZip', notes: [] },
    { v: 'v1.21.0', date: '2026-08-25', title: 'Duplikat-Erkennung + SW-Cache-Fix', notes: [] },
    { v: 'v1.20.0', date: '2026-08-25', title: 'Produkt-Seite Bugfix + Server-Filter', notes: [] },
    { v: 'v1.19.0', date: '2026-08-25', title: 'Blog, Wochenziel-History, Produkt-Statistik', notes: [] },
    { v: 'v1.12.1', date: '2026-08-14', title: 'Erweiterte Kategorien-Liste (~70)', notes: [] },
    { v: 'v1.12.0', date: '2026-08-14', title: 'Item-Split, Preisvergleich pro Laden', notes: [] },
    { v: 'v1.11.2', date: '2026-08-14', title: 'Produkt-History-Modal + Detach', notes: [] },
    { v: 'v1.11.1', date: '2026-08-14', title: 'Fix Pool-Release, Preisverlauf-UI', notes: [] },
    { v: 'v1.11.0', date: '2026-08-14', title: 'Reparse-All, 3-Spalten-Items', notes: [] },
    { v: 'v1.10.2', date: '2026-08-14', title: 'main.py aufgeteilt + Health-Endpoint', notes: [] },
    { v: 'v1.10.0', date: '2026-08-14', title: 'Suche, Presets, Undo/Swipe, Preis-Chart', notes: [] },
    { v: 'v1.9.0',  date: '2026-08-14', title: 'Preisverlauf-Tab, globale Subnav', notes: [] },
    { v: 'v1.8.6',  date: '2026-08-14', title: 'Dashboard-Inline-Detail, Upload-Buttons', notes: [] },
    { v: 'v1.8.5',  date: '2026-08-14', title: 'Gemini 3.5-flash-lite Default', notes: [] },
    { v: 'v1.8.2',  date: '2026-08-14', title: 'AI liefert category_name', notes: [] },
    { v: 'v1.7.2',  date: '2026-08-13', title: 'BILLA-Parser (AT-Stores)', notes: [] },
    { v: 'v1.7.1',  date: '2026-08-13', title: 'SW-redirect-fix (iOS), expense_type', notes: [] },
    { v: 'v0.x',    date: '2026-08-08', title: 'Projekt-Setup + erste Version', notes: [
        'Initial commit, erste AI-BON-Erkennung, mehrere Parser-Iterationen.',
    ]},
];
