/* changelog.js — v1.38.0
 * Statisch generierte Versions-Historie fuer den vertikalen Zeitstrahl,
 * der beim Klick auf .version-tag angezeigt wird.
 * Neue Releases OBEN einfuegen.
 */
window.VEXBOB_CHANGELOG = [
    { v: 'v1.43.2', date: '2026-09-04', title: 'Ø Puls über alle Workouts ist zurück — diesmal richtig gerechnet', notes: [
        'Die Ø-Puls-Kachel im Workouts-Tab gibt es wieder. Sie mittelt nur noch Workouts, die überhaupt einen plausiblen Pulswert mitbringen (30–240 bpm), und schreibt in die Unterzeile, auf wie vielen Workouts der Schnitt beruht — statt stillschweigend über Nullwerte oder Millisekunden zu mitteln.',
        'Migration 029 räumt die Altlasten weg: Pulswerte außerhalb 30–240 bpm werden auf NULL gesetzt. Das betrifft genau die Zeilen, in denen der Import die HRV-Spalte (ms) als Puls gespeichert hat. Ein erneuter Import füllt den echten Wert wieder auf.',
        'Der Import verwirft unplausible Pulswerte jetzt schon beim Schreiben — sowohl beim CSV- als auch beim REST-API-Weg. Lieber kein Puls als ein falscher, der jeden Durchschnitt darüber kippt.',
    ]},
    { v: 'v1.43.1', date: '2026-09-04', title: 'Workout-Kennzahlen mit Zeitfilter, Ideen-Sammlung aufgeraeumt', notes: [
        'Der Ø-Puls über allen Workouts stand bei 8 bpm. Grund: Der CSV-Import hat die Spalte „Durchschn. Herzfrequenzvariabilität (ms)" als Puls-Spalte erkannt, weil sie sowohl „Durchschn." als auch „Herzfrequenz" enthält und im Export vor der echten Puls-Spalte steht. HRV-Spalten werden bei der Puls-Suche jetzt übersprungen — bereits importierte Workouts brauchen dafür einen erneuten Import.',
        'Die Workout-Kennzahlen zeigen jetzt Gesamtzeit, Ø Dauer und Ø Kalorien (aktiv). Anzahl und Ø Puls sind raus. Die Durchschnitte rechnen nur über Workouts, die den Wert wirklich mitbringen.',
        'Neu im Workouts-Tab: Zeitraum-Filter (30 Tage / 90 Tage / 12 Monate / Gesamt) neben den Sportart-Chips. Die Kennzahlen beziehen sich auf den gewählten Zeitraum, die Überschrift der Liste nennt ihn.',
        'Sparziele: Die Kachel „Noch offen" ist raus.',
        'Ideen-Sammlung: Einträge stehen jetzt als Zeilen wie die Wunschliste statt als Chip-Wolke. Die freie Kategorie ist durch eine feste Auswahl ersetzt — ohne, Meilenstein oder Wochenziel; nur diese beiden werden noch als Tag angezeigt.',
    ]},
    { v: 'v1.43.0', date: '2026-09-04', title: 'Abgeschlossene Sparziele verschwinden wirklich — ohne Platzhalter-Ziel', notes: [
        'Ein abgeschlossenes Sparziel wird jetzt gelöscht statt auf 0 zurückgesetzt. Bisher blieb es unter „Meine Sparziele" als leere Hülle stehen, obwohl es längst als Trophäe an der Wand hing.',
        'Das automatisch angelegte „Neues Sparziel" über 100 € ist raus. Nach dem Abschließen ist bewusst kein Ziel aktiv — jede Belohnung aus Achievements und Wochenzielen läuft dann in den Puffer, bis du selbst ein neues Ziel anlegst oder ein pausiertes aktivierst.',
        'Passend dazu: Ein aktives Ziel lässt sich per „Pausieren" beenden, ohne dass ein anderes einspringt, und auch das letzte Sparziel darf gelöscht werden. Beim Löschen wird kein zufälliges anderes Ziel mehr aktiviert (im Zweifel war das sogar der Puffer).',
        'Das Dashboard zeigt in diesem Zustand keinen 0-%-Ring mehr, sondern den Puffer mit Stand, Erklärung und Direktknopf zum Anlegen eines Ziels. Der Sparverlauf-Chart zeigt dann den Puffer statt leer zu bleiben.',
        'Der Tab „Ideen & Ziele" ist neu gebaut: Kennzahlen-Leiste (aktives Ziel, Summe auf Zielen, Puffer, offener Rest), eigene Puffer-Karte, Sparziel-Karten mit Fortschrittsbalken, Prozent, Restbetrag und Status-Pille sowie klar getrennte Abschnitte für Wunschliste und Ideen-Sammlung mit Zähler und Kurzbeschreibung.',
        'Neu in der Wunschliste: „→ Sparziel" übernimmt Name und Preis eines Wunsches direkt ins Anlege-Formular.',
    ]},
    { v: 'v1.42.0', date: '2026-09-03', title: 'Preisverlauf entfernt, Produkte gruppieren jetzt über Läden hinweg', notes: [
        'Die Preisverlauf-Seite und der normierte Preisvergleich sind raus. Er hat Artikel miteinander verrechnet, deren Einheiten gar nicht vergleichbar waren: fehlte die Mengeneinheit oder stand auf dem Bon "1 Pack" statt "500 g", landete ein €/Stück-Wert im selben Ø wie die €/kg-Werte — samt erfundener Preissprünge und falschem "günstigster Laden"-Ranking.',
        'Die Produkte-Seite bleibt und zeigt jetzt echte Zahlen: tatsächlich bezahlte Summe statt hochgerechnetem Ø-Einheitspreis, und pro Produkt ALLE Läden nebeneinander statt nur den letzten.',
        'Neu: Zusammenführen-Vorschläge. "Gouda", "Gouda jung" und "Goudakäse" waren drei Zeilen, weil jeder Laden anders auf den Bon druckt. Der Server erkennt solche Schreibvarianten (Präfix bzw. enthaltene Wortmenge — nie über ein zufällig geteiltes Adjektiv) und schlägt sie zum Zusammenführen vor; ein Klick schreibt allen Positionen dieselbe Gruppe, dauerhaft auch für künftige Käufe. Abgelehnte Vorschläge kommen nicht wieder (Migration 028).',
        'Import: Mengeneinheiten gehen nicht mehr verloren. Lieferte die KI "Haferflocken 500g" nur im Namen, hat der Parser das "500g" aus dem Namen geschnitten und weggeworfen — jetzt landet es in Menge/Einheit. Synonyme wie Liter, Gramm, Stück, Packung, Rolle oder Dose werden zugeordnet statt still verworfen.',
        '"Alle neu parsen" ist von der Preisverlauf- auf die Produkte-Seite umgezogen; der Bon-Toggle heißt jetzt "aus der Produktliste ausblenden" statt "aus dem Preisvergleich".',
    ]},
    { v: 'v1.41.1', date: '2026-09-03', title: 'Log-Notizen brechen auf dem Handy nicht mehr auf ein Zeichen pro Zeile um', notes: [
        'Die Notiz war das einzige schrumpfbare Element einer Log-Zeile: neben Tag, Titel, Betrag und den beiden Buttons blieb auf schmalen Displays eine Spalte von wenigen Pixeln übrig — der Text brach senkrecht auf ein Zeichen pro Zeile um und ein einzelner Eintrag wurde meterhoch.',
        'Unter 700 px Breite steht die Notiz jetzt in einer eigenen, vollbreiten Zeile unter dem Eintrag, linksbündig. Betrag, Notiz- und Löschen-Button bleiben oben in der ersten Zeile.',
        'Ab 700 px bleibt die gewohnte einzeilige Darstellung; sie kann jetzt aber sauber umbrechen statt zu quetschen. Sehr lange Wörter (URLs) brechen mit overflow-wrap statt die Zeile zu sprengen.',
    ]},
    { v: 'v1.41.0', date: '2026-09-03', title: 'Log zeigt jede Wertänderung an Achievements', notes: [
        'Bisher landete eine Änderung am Meilenstein-Ziel nur dann im Aktivitäts-Log, wenn sie eine Meilenstein-Schwelle überschritten hat — der "+x"-Button und das manuelle Setzen des Werts haben darunter nichts hinterlassen. Jede Änderung wird jetzt protokolliert (neue Tabelle achievement_progress_logs, Migration 027).',
        'Neuer Log-Typ "Fortschritt" mit eigenem Filter-Chip: zeigt Vorher → Nachher und in der Betragsspalte die Änderung selbst (z.B. "+2,5 km"). Ausgezahlt wird weiterhin nur beim Meilenstein, diese Zeilen tragen keinen Betrag.',
        'Notizen sind wie bei allen anderen Log-Einträgen möglich. Zurücknehmen lässt sich die jeweils letzte Änderung eines Ziels — sie setzt den Wert wieder auf den Stand davor; hat die Änderung einen Meilenstein ausgelöst, geht das über den Meilenstein-Eintrag.',
    ]},
    { v: 'v1.40.5', date: '2026-09-03', title: 'Schwimm-Pace in min/100 m, Distanz-Einheit korrigiert', notes: [
        'Die Workouts-CSV beschriftet die Distanz-Spalte immer mit "(km)", liefert beim Schwimmen aber Meter — 1800 wurde dadurch als 1800 km importiert und die Pace-Kachel zeigte 0:02 min/km. Der Import erkennt Meter-Zeilen jetzt an der Größenordnung (über 300 km bzw. über 100 km/h Ø-Geschwindigkeit) und rechnet Distanz und Geschwindigkeit gemeinsam um.',
        'Migration 026 zieht bereits importierte Workouts nach: unplausible Distanzen und Ø-/Max-Geschwindigkeiten werden durch 1000 geteilt.',
        'Schwimm-Workouts zeigen die Pace jetzt in min/100 m statt min/km (1800 m in 1:08:21 = 3:48 min/100 m) und die Distanz in Metern statt Kilometern.',
        'APP_VERSION war seit v1.40.3 versehentlich leer und ist wiederhergestellt — der Versions-Tag im Footer blieb dadurch leer.',
    ]},
    { v: 'v1.40.4', date: '2026-09-02', title: 'README: Funktionen einzeln beschrieben', notes: [
        'Die Modul-Übersicht besteht nicht mehr aus dichten Aufzählungs-Absätzen, sondern listet jede Funktion einzeln — mit einem Satz dazu, was sie tut und wozu sie da ist.',
        'Neu dokumentiert: Import-Protokoll und Messlücken-Regeln im Gesundheits-Modul, Bons-kompakt-Sektion im aggregierten Gesamt-Export, Puffer-Konto, Ideen-Listen und Duplikat-Erkennung.',
    ]},
    { v: 'v1.40.3', date: '2026-09-02', title: 'Schlaf-Diagramm zeigt die Gesamtschlafzeit', notes: [
        'Der Balken steht jetzt für die geschlafene Gesamtzeit der Nacht — die Phasen sind nur noch die Binnenzeichnung in vier Helligkeitsstufen derselben Farbe, damit zuerst die Gesamthöhe lesbar ist.',
        '"Wach" ist nicht mehr Teil des Stapels: Wachzeit ist kein Schlaf und hat den Balken über die tatsächliche Schlafdauer hinaus aufgeblasen. Sie steckt weiterhin in der Ø-Effizienz.',
        'Neues Segment "ohne Phasendetail" fängt den Anteil ab, den Apple ohne Phasen-Zuordnung liefert — dadurch entspricht die Balkenhöhe exakt der Ø-Schlafdauer-Kachel.',
        'Die Nächte unter 1 h Schlaf (v1.40.2) fliegen jetzt auch aus beiden Schlaf-Diagrammen, nicht mehr nur aus den Ø-Kacheln.',
    ]},
    { v: 'v1.40.2', date: '2026-09-02', title: 'Schlaf: Nächte unter 1 h zählen nicht mehr in den Ø', notes: [
        'Nächte mit weniger als 1 Stunde Gesamtschlaf (Apple Watch nicht getragen, zu spät angelegt, Schlaf-Fragment) fallen aus allen vier Ø-Kacheln des Schlaf-Tabs: Ø Schlafdauer, Ø Im Bett, Ø Tiefschlaf und Ø Effizienz.',
        'Entscheidend ist die gesamte Schlafdauer der Nacht, nicht die einzelne Phase — sonst würden sich die vier Kacheln auf unterschiedliche Nächte beziehen.',
        'Im Schlafphasen-Diagramm bleiben diese Nächte sichtbar; unter den Kacheln steht, wie viele ausgenommen wurden.',
    ]},
    { v: 'v1.40.1', date: '2026-09-02', title: 'Gesamt-Export: Einkäufe bleiben auch bei Wochen-/Monats-Aggregation drin', notes: [
        'Bei aggregate=week|month stand bisher nur die Perioden-Summe in der CSV — jetzt folgt darunter eine Sektion "Bons kompakt" mit einer Zeile je Einkauf: Woche/Monat, Datum, Laden, Typ, Anzahl Positionen, Gesamtbetrag und die Produktkategorien mit Anzahl und Betrag.',
        'Die Einzelpositionen bleiben in diesem Modus weiterhin weg — damit bleibt erkennbar, wofür das Geld ausgegeben wurde, ohne dass ein Jahres-Export auf über 10.000 Zeilen anwächst.',
    ]},
    { v: 'v1.40.0', date: '2026-09-02', title: 'Gesundheit: Import-Protokoll mit Payload-Download', notes: [
        'Jeder automatische Sync der Auto-Health-Export-App wird jetzt mit seinem Roh-Payload gespeichert (neue Tabelle health_import_log, Migration 025).',
        'Neue Karte "Import-Protokoll" in den Gesundheits-Einstellungen: Zeitpunkt, Format, Dateiname, Größe, Ingest-Ergebnis und Vorschau je Aufruf — plus Download der Originaldatei zum Abgleich mit den importierten Werten.',
        'Einzelne Einträge löschbar, Protokoll komplett leerbar. Aufbewahrt werden die letzten 200 Aufrufe je Nutzer, Payloads über 5 MB werden gekürzt (ENV HEALTH_IMPORT_LOG_KEEP / HEALTH_IMPORT_LOG_MAX_BYTES).',
    ]},
    { v: 'v1.39.2', date: '2026-09-01', title: 'Vitalwerte: Ø-Linie als gleitender Trend', notes: [
        'Die Ø-Linie ist keine Waagrechte mehr, sondern ein zentriert gleitender Durchschnitt, der dem Verlauf folgt.',
        'Fensterbreite passt sich dem Zeitraum an (3 / 7 / 14 / 30 Werte), Messlücken bleiben weiterhin aussen vor.',
    ]},
    { v: 'v1.39.1', date: '2026-09-01', title: 'Gesundheit: Schlaf-Dopplung weg, Ø-Linie bei Vitalwerten', notes: [
        'Der kleine Schlaf-Insight auf der Übersicht ist entfallen — er rechnete mit den rohen asleep_minutes und zeigte daher weniger an als die Karte "Letzte Nacht" direkt daneben.',
        'Vitalwerte-Verlauf hat jetzt eine gestrichelte Ø-Linie.',
        'Ø, Min und Max ignorieren Messlücken: Werte unter 20 % des Medians (angebrochener heutiger Tag, Uhr nicht getragen, abgebrochener Sync) zählen nicht als Messwert. Die Anzahl ausgenommener Tage steht in der Statistikzeile.',
    ]},
    { v: 'v1.39.0', date: '2026-09-01', title: 'Duplikate: eigener Tab + ausblendbare Vorschläge', notes: [
        'Neue Seite "♻️ Duplikate" im Ausgaben-Subnav statt Karte auf dem Dashboard.',
        'Jeder Vorschlag hat jetzt ein "✕" zum dauerhaften Ausblenden, ohne die Bons zu löschen oder zusammenzuführen (neue Tabelle dismissed_expense_duplicates, Migration 024).',
    ]},
    { v: 'v1.38.7', date: '2026-09-01', title: 'Ausgaben-Übersicht: nur letzte 14 Tage + Aufklappen', notes: [
        'Dashboard-Liste zeigt standardmäßig nur Bons der letzten 14 Tage, darunter Button "Alle anzeigen" für ältere Einträge.',
        'Gilt nur ohne aktive Filter — sobald Zeitraum/Laden/Kategorie/Suche gesetzt ist, werden wie bisher alle Treffer direkt angezeigt.',
    ]},
    { v: 'v1.38.6', date: '2026-09-01', title: 'README komplett überarbeitet', notes: [
        'Von Changelog-artiger Feature-Liste (Versionsnummern in jedem Bullet) auf prägnante Beschreibung des aktuellen Stands umgestellt.',
        'Fehler behoben: Quickstart nannte JWT_SECRET statt korrektem ENV-Namen SECRET_KEY, Pfade zeigten auf nicht mehr existierendes Website/-Verzeichnis.',
        'Projekt-Struktur, Routers-Liste und Modul-Übersicht an tatsächlichen Code-Stand angeglichen (Blog ergänzt, veraltete Verweise entfernt).',
    ]},
    { v: 'v1.38.5', date: '2026-09-01', title: 'README aufgeräumt (Rezeptbuch/Fotos entfernt)', notes: [
        'Nie umgesetzte Platzhalter-Module Rezeptbuch und Fotos aus README (Subtitel, Feature-Liste, Projekt-Struktur) entfernt — beide waren nur "Coming soon"-Seiten ohne Backend oder Navigation.',
    ]},
    { v: 'v1.38.4', date: '2026-09-01', title: 'Sichtbare File-Inputs und Subnav-Rest weg', notes: [
        'Versteckte <input type=file>-Felder wurden von der globalen Form-Base ungewollt sichtbar gemacht — [hidden] jetzt mit !important abgesichert.',
        '"+ Neuer Bon"-Eintrag aus der Ausgaben-Subnav entfernt (jetzt nur noch ueber die Dashboard-Tiles).',
    ]},
    { v: 'v1.38.3', date: '2026-09-01', title: 'Neuer-Bon-Tiles im Homepage-Design', notes: [
        '4 Tiles im gleichen Look wie das Homepage-Dashboard: farbiges Icon-Badge + Titel + Kurztext.',
        'Kaste "Datei durchsuchen / hierher ziehen" entfernt.',
        'Drag & Drop laeuft jetzt unsichtbar auf der ganzen Seite mit temporaerem Overlay, das nur beim Draggen erscheint.',
    ]},
    { v: 'v1.38.2', date: '2026-09-01', title: 'Ausgaben-Dashboard: Neuer Bon direkt integriert', notes: [
        'Popup/Modal + FAB fuer "Neuer Bon" entfernt.',
        'Stattdessen Quick-Action-Karte oben im Dashboard: Kamera, Galerie, Einfuegen, Manuell.',
        'Drag & Drop-Zone und globaler Strg+V-Handler auf dem Dashboard.',
        'Bilder werden per sessionStorage an neu.html?src=dash uebergeben und starten dort automatisch den OCR-Flow.',
    ]},
    { v: 'v1.38.1', date: '2026-09-01', title: 'Hotfix: Ausgaben-Dashboard lud nicht', notes: [
        'Syntax-Fehler in dashboard.js (fehlende schliessende Klammer in renderActiveFilterChips) behoben — Seite blieb dadurch unsichtbar (body.visibility:hidden).',
    ]},
    { v: 'v1.38.0', date: '2026-09-01', title: 'Ausgaben-UX + Versions-Zeitstrahl', notes: [
        'Filter im Ausgaben-Dashboard hinter einem Popover versteckt (Suche + Presets bleiben sichtbar).',
        'Aktive Filter erscheinen als Zahl-Badge am Filter-Button.',
        '"+ Neuer Bon" oeffnet ein Modal direkt im Dashboard statt einer eigenen Seite.',
        'Klick auf die Versionszahl unten rechts oeffnet einen vertikalen Zeitstrahl mit allen Releases.',
    ]},
    { v: 'v1.37.2', date: '2026-08-31', title: 'Export-Aggregation korrekt', notes: [
        'Fix: bei aggregate=week|month wurden nicht alle Bereiche zusammengefasst.',
    ]},
    { v: 'v1.37.1', date: '2026-08-31', title: 'Zeitraum + Aggregation im Gesamt-Export', notes: [] },
    { v: 'v1.37.0', date: '2026-08-31', title: 'Toast/Confirm, Mobile Tab-Bar, SVG-Theme-Icon', notes: [
        'Modul-uebergreifender Toast/Confirm-Layer, Bottom-Tab-Bar auf Mobile.',
    ]},
    { v: 'v1.36.1', date: '2026-08-29', title: 'Schlaf-Fix + Icon-only Modul-Switcher', notes: [] },
    { v: 'v1.36.0', date: '2026-08-29', title: 'Design-Refresh (Glass Navbar, Hero, iOS-Tabs)', notes: [] },
    { v: 'v1.35.0', date: '2026-08-29', title: 'Migration-Checksums, Dry-Run, Sentry-Hook', notes: [] },
    { v: 'v1.34.0', date: '2026-08-29', title: 'Observability + Readiness-Probe', notes: [] },
    { v: 'v1.33.0', date: '2026-08-29', title: 'Backend-Haertung (Pool-Race, Timing-Attack, JSON)', notes: [] },
    { v: 'v1.32.0', date: '2026-08-29', title: ':where()-Form-Base, .btn-Utility, weg mit !important', notes: [] },
    { v: 'v1.31.0', date: '2026-08-29', title: 'CSS-Auslagerung, Print/Touch/SEO', notes: [] },
    { v: 'v1.30.0', date: '2026-08-29', title: 'P0/P1 CSS-Fixes (A11y, FOUC, Design-Tokens)', notes: [] },
    { v: 'v1.29.2', date: '2026-08-28', title: 'CSV-Exports mit UTF-8-BOM', notes: [] },
    { v: 'v1.29.1', date: '2026-08-28', title: 'Fix Schlaf-KPIs bei fehlenden Werten', notes: [] },
    { v: 'v1.29.0', date: '2026-08-28', title: 'CSV-Import 1:1, Rescale entfernt', notes: [] },
    { v: 'v1.28.1', date: '2026-08-28', title: 'Fix Startup-Crash (slowapi)', notes: [] },
    { v: 'v1.28.0', date: '2026-08-28', title: 'Health-Datensaetze loeschen', notes: [] },
    { v: 'v1.27.0', date: '2026-08-28', title: 'Health-CSV im Gesamt-Export', notes: [] },
    { v: 'v1.26.0', date: '2026-08-28', title: 'Uebertrag vom Puffer aufs Sparziel', notes: [] },
    { v: 'v1.25.1', date: '2026-08-28', title: 'Workouts inline + Schlaf-Empty-State', notes: [] },
    { v: 'v1.25.0', date: '2026-08-28', title: 'Health-Seite modernisiert', notes: [] },
    { v: 'v1.24.0', date: '2026-08-28', title: 'CSV-basierter Health-Import', notes: [] },
    { v: 'v1.23.2', date: '2026-08-28', title: 'Hotfix Crash-Loop (health_router)', notes: [] },
    { v: 'v1.23.1', date: '2026-08-28', title: 'Manueller JSON-Import (Health)', notes: [] },
    { v: 'v1.23.0', date: '2026-08-28', title: 'Gesamt-Export (Sparziel+Ausgaben+Health)', notes: [] },
    { v: 'v1.22.1', date: '2026-08-28', title: 'Fix: hKeyModal blockierte Klicks', notes: [] },
    { v: 'v1.22.0', date: '2026-08-28', title: 'Health-Modul (Auto Health Export Sync)', notes: [] },
    { v: 'v1.21.3', date: '2026-08-26', title: 'Fix Produkte-Seite unsichtbar', notes: [] },
    { v: 'v1.21.2', date: '2026-08-26', title: 'Fix HTTP 500 auf Produkt-Seite', notes: [] },
    { v: 'v1.21.1', date: '2026-08-26', title: 'SW Auto-Update, Blog-Menue, GZip', notes: [] },
    { v: 'v1.21.0', date: '2026-08-25', title: 'Duplikat-Erkennung + SW-Cache-Fix', notes: [] },
    { v: 'v1.20.0', date: '2026-08-25', title: 'Produkt-Seite Bugfix + Server-Filter', notes: [] },
    { v: 'v1.19.0', date: '2026-08-25', title: 'Blog, Wochenziel-History, Produkt-Statistik', notes: [] },
    { v: 'v1.12.1', date: '2026-08-14', title: 'Erweiterte Kategorien-Liste (~70)', notes: [] },
    { v: 'v1.12.0', date: '2026-08-14', title: 'Item-Split, Preisvergleich pro Laden', notes: [] },
    { v: 'v1.11.2', date: '2026-08-14', title: 'Produkt-History-Modal + Detach', notes: [] },
    { v: 'v1.11.1', date: '2026-08-14', title: 'Fix Pool-Release, Preisverlauf-UI', notes: [] },
    { v: 'v1.11.0', date: '2026-08-14', title: 'Reparse-All, 3-Spalten-Items', notes: [] },
    { v: 'v1.10.2', date: '2026-08-14', title: 'main.py aufgeteilt + Health-Endpoint', notes: [] },
    { v: 'v1.10.0', date: '2026-08-14', title: 'Suche, Presets, Undo/Swipe, Preis-Chart', notes: [] },
    { v: 'v1.9.0',  date: '2026-08-14', title: 'Preisverlauf-Tab, globale Subnav', notes: [] },
    { v: 'v1.8.6',  date: '2026-08-14', title: 'Dashboard-Inline-Detail, Upload-Buttons', notes: [] },
    { v: 'v1.8.5',  date: '2026-08-14', title: 'Gemini 3.5-flash-lite Default', notes: [] },
    { v: 'v1.8.2',  date: '2026-08-14', title: 'AI liefert category_name', notes: [] },
    { v: 'v1.7.2',  date: '2026-08-13', title: 'BILLA-Parser (AT-Stores)', notes: [] },
    { v: 'v1.7.1',  date: '2026-08-13', title: 'SW-redirect-fix (iOS), expense_type', notes: [] },
    { v: 'v0.x',    date: '2026-08-08', title: 'Projekt-Setup + erste Version', notes: [
        'Initial commit, erste AI-BON-Erkennung, mehrere Parser-Iterationen.',
    ]},
];
